spec:
  replicas: 2
  template:
    spec:
      containers:
        - 
          env:
          - name: SPRING_APPLICATION_NAME
            value: camel-cloud-svc
          - name: POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
