server:
  address: 127.0.0.1
management:
  address: 0.0.0.0
  port: 8081
endpoints:
  enabled: false
  health:
    enabled: true

spring:
  main:
    web-environment: false

camel:
  springboot:
    main-run-controller: true

