spec:
  replicas: 1
  template:
    spec:
      containers:
        - 
          env:
          - name: SPRING_APPLICATION_NAME
            value: camel-cloud-service-consumer
          - name: SERVICE_NAME
            value: camel-cloud-service
